<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyuEh55\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyuEh55/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHyuEh55.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHyuEh55\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHyuEh55\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HyuEh55',
    'container.build_id' => '2a6fb297',
    'container.build_time' => 1652616096,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyuEh55');
