<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvpBxSx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvpBxSx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVvpBxSx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVvpBxSx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVvpBxSx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VvpBxSx',
    'container.build_id' => 'ede25cc3',
    'container.build_time' => 1649314759,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvpBxSx');
