<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZF894c3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZF894c3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZF894c3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZF894c3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZF894c3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZF894c3',
    'container.build_id' => 'dcfc45b4',
    'container.build_time' => 1652755209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZF894c3');
